stages:
  - deploy
deploy:
  stage: deploy
  tags:
    - gitlab-org
  image: mwienk/docker-lftp:latest
  script:
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rnev ${REPRO_FOLDER} ${FTP_FOLDER} --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/ --exclude .env"
  only:
    - master